In [26]:
import pandas as pd 

In [2]:
data = pd.read_csv('wine-quality-engrd.csv', sep=';')

###  Data Inspection

In [27]:
data.shape

(1599, 17)

In [28]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,free_sulfur_ratio,acidity_balance,log_residual_sugar,is_high_alcohol,acidity_level
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0.323529,10.571413,1.064711,0,medium
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0.373134,8.863626,1.280934,0,medium
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0.277778,10.263144,1.193922,0,medium
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0.283333,39.999857,1.064711,0,high
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0.323529,10.571413,1.064711,0,medium


In [31]:
# Checking the columns...
data.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1519 non-null   float64
 9   sulphates             1549 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
 12  free_sulfur_ratio     1599 non-null   float64
 13  acidity_balance       1599 non-null   float64
 14  log_residual_sugar    1599 non-null   float64
 15  is_high_alcohol      

In [32]:
# Getting the null count of each column to know the percentage
data.isna().sum().sort_values()

fixed acidity            0
volatile acidity         0
citric acid              0
residual sugar           0
chlorides                0
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
quality                  0
alcohol                  0
acidity_balance          0
free_sulfur_ratio        0
log_residual_sugar       0
is_high_alcohol          0
acidity_level            0
sulphates               50
pH                      80
dtype: int64

In [33]:
# Want to sure that np.nan is the missing value and none has sneaked passed the checks

data['pH'].unique(), '\n\n\n', data['sulphates'].unique()

(array([3.51, 3.2 , 3.26, 3.16, 3.3 , 3.39, 3.36, 3.35, 3.28, 3.58, 3.17,
        3.11, 3.38, 3.04, 3.52, 3.43, 3.34, 3.47, 3.46, 3.45, 3.4 , 3.42,
        3.23, 3.5 , 3.33, 3.21, 3.48, 3.9 , 3.25, 3.32, 3.15, 3.41, 3.44,
         nan, 3.31, 3.54, 3.13, 2.93, 3.14, 3.75, 3.85, 3.29, 3.37, 3.19,
        3.07, 3.49, 3.53, 3.24, 3.63, 3.22, 3.68, 2.74, 3.59, 3.  , 3.12,
        3.57, 3.08, 3.61, 3.06, 3.6 , 3.69, 3.1 , 3.05, 3.67, 3.27, 3.18,
        3.02, 3.55, 2.99, 3.01, 3.56, 3.03, 3.62, 2.88, 2.95, 2.98, 3.09,
        2.86, 3.74, 2.92, 3.72, 2.87, 2.89, 2.94, 3.66, 3.71, 3.78, 3.7 ,
        4.01, 2.9 ]),
 '\n\n\n',
 array([0.56, 0.68, 0.65, 0.58, 0.46, 0.47, 0.57, 0.8 , 0.54, 0.52, 1.56,
        0.88, 0.93, 0.75, 1.28, 0.5 , 1.08, 0.53, 0.91, 0.63, 0.59, 0.55,
        0.66,  nan, 0.6 , 0.73, 0.48, 0.83, 0.51, 0.9 , 1.2 , 0.74, 0.64,
        0.77, 0.71, 0.62, 0.39, 0.79, 0.95, 0.82, 1.12, 1.14, 0.78, 1.95,
        1.22, 1.98, 0.61, 1.31, 0.69, 0.67, 0.7 , 0.49, 0.92, 2.  , 0.72,
     

In [34]:
# Checking the target values
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

### 2. Splitting the data into features and traget

In [35]:
from sklearn.model_selection import train_test_split

features = ['volatile acidity', 'citric acid', 'residual sugar', 'chlorides',
            'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH',
            'sulphates', 'alcohol', 'free_sulfur_ratio', 'acidity_balance',
            'log_residual_sugar', 'is_high_alcohol', 'acidity_level']

# X = data[features]

X=data.drop(['quality'], axis=1) # axis = 1 drops the quality column
y = data['quality']

# CRITICAL: split BEFORE fitting any transformer
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print('Train size:', X_train.shape, '| Test size:', X_test.shape)

Train size: (1279, 16) | Test size: (320, 16)


### Defining the pipeline

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# ── Identify column types ────────────────────────────────────────────────────
numeric_features = ['volatile acidity', 'citric acid', 'residual sugar',
                    'chlorides', 'free sulfur dioxide', 'total sulfur dioxide',
                    'density', 'pH', 'sulphates', 'alcohol',
                    'free_sulfur_ratio', 'acidity_balance',
                    'log_residual_sugar', 'is_high_alcohol']

categorical_features = ['acidity_level']


# ── Numeric pipeline: impute then scale ──────────────────────────────────────
numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),   # robust to outliers
    ('scaler',  StandardScaler())                    # zero mean, unit variance
])

# ── Categorical pipeline: impute then encode ─────────────────────────────────
categorical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

# ── ColumnTransformer: apply each pipeline to the right columns ───────────────
preprocessor = ColumnTransformer(transformers=[
    ('numeric_pipeline', numeric_pipeline, numeric_features),
    ('categorical_pipeline', categorical_pipeline, categorical_features)
])

### Building 

In [36]:
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import RandomizedSearchCV


logreg = LogisticRegression(l1_ratio=0, C=0.8, max_iter=4000)

ridge = RidgeClassifier(alpha=0.3)

knn = KNeighborsClassifier(n_neighbors=1)

full_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('estimator', knn)
])

# ONE call — fit preprocessor and model together on training data only
full_pipeline.fit(X_train, y_train)

# Predict on test set — preprocessor transforms with train statistics
y_pred = full_pipeline.predict(X_test)

print('Accuracy:', round(accuracy_score(y_test, y_pred), 4))
print('\nClassification Report:')
print(classification_report(y_test, y_pred, zero_division=0))



Accuracy: 0.6312

Classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.10      0.09      0.10        11
           5       0.73      0.72      0.73       136
           6       0.61      0.62      0.61       128
           7       0.53      0.57      0.55        40
           8       0.25      0.33      0.29         3

    accuracy                           0.63       320
   macro avg       0.37      0.39      0.38       320
weighted avg       0.63      0.63      0.63       320

